### Alle Spots abrufen
GET http://localhost:8081/api/spots
Accept: application/json

### Eigenen Spots abrufen
GET http://localhost:8081/api/spots/mine?user=Marie
Accept: application/json

### Neuen Spot erstellen
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "name": "Hafen",
  "description": "Schöner Park am Fluss",
  "createdBy": "Efe-liz",
  "location": "Konstanz"
}

### Neuen Spot erstellen
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "title": "Seerhein Park",
  "description": "Schöner Park am Fluss",
  "image": "",
  "tags": "Seerhein"
}

### Neuen Spot erstellen 
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "title": "Seerhein Park",
  "description": "Schöner Park am Fluss",
  "imageUrl": "https://example.com/bild.jpg",
  "category": "Park",
  "location": "Konstanz"
}


### Neuen Spot erstellen 
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "title": "Seerhein Park",
  "description": "Schöner Park am Fluss",
  "imageUrl": "https://example.com/bild.jpg",
  "category": "Park",
  "location": "Konstanz"
}


### Neuen Spot erstellen 
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "title": "Hafen",
  "description": "Schöner Hafen mit Booten",
  "imageUrl": "https://example.com/bild.jpg",
  "category": "Natur und Aussicht",
  "location": "Konstanz"
}

### Neuen Spot erstellen 
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "title": "Campus Festival",
  "description": "Großes Event im Bodenseestadion mit tollen Acts.",
  "imageUrl": "https://example.com/bild.jpg",
  "category": "Events und Kultur",
  "location": "Konstanz"
}

### Spot aktualisieren
PUT http://localhost:8081/api/spots/6
Content-Type: application/json

{
  "name": "Hafen Konstanz Updated",
  "description": "Schöner Hafen mit Restaurants und Cafés",
  "createdBy": "Moritz",
  "location": "Hafenstraße 1"
}

### Spot löschen
DELETE http://localhost:8081/api/spots/4



### Alle Reviews eines Spots abrufen
GET http://localhost:8081/api/reviews/spot/4
Accept: application/json

### Neue Review erstellen
POST http://localhost:8081/api/reviews
Content-Type: application/json

{
  "spotId": 4,
  "rating": 5,
  "comment": "Super Spot!"
}

### Review löschen
DELETE http://localhost:8081/api/reviews/4

mvn spring-boot:run -Dspring-boot.run.profiles=local