### Alle Spots abrufen
GET http://localhost:8081/api/spots
Accept: application/json

### Eigenen Spots abrufen
GET http://localhost:8081/api/spots/mine?user=Moritz
Accept: application/json

### Neuen Spot erstellen
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "name": "Seerhein Park",
  "description": "Schöner Park am Fluss",
  "createdBy": "Moritz",
  "location": "Seerhein"
}

### Neuen Spot erstellen
POST http://localhost:8081/api/spots
Content-Type: application/json

{
  "name": "Seerhein Park",
  "description": "Schöner Park am Fluss",
  "createdBy": "Marie",
  "location": "Seerhein"
}

### Spot aktualisieren
PUT http://localhost:8081/api/spots/1
Content-Type: application/json

{
  "name": "Hafen Konstanz Updated",
  "description": "Schöner Hafen mit Restaurants und Cafés",
  "createdBy": "Moritz",
  "location": "Hafenstraße 1"
}

### Spot löschen
DELETE http://localhost:8081/api/spots/1



### Alle Reviews eines Spots abrufen
GET http://localhost:8081/api/reviews/spot/4
Accept: application/json

### Neue Review erstellen
POST http://localhost:8081/api/reviews
Content-Type: application/json

{
  "spotId": 4,
  "rating": 5,
  "comment": "Super Spot!"
}

### Review löschen
DELETE http://localhost:8081/api/reviews/4
